coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 0.1%
        if_ci_failed: error
        if_not_found: success
        only_pulls: true
      patch:
        default:
          target: 95%
