name: CI - Unit testing

on:
  push:
    branches:
      - main
    paths:
      - 'src/**/*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Test and upload code coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install
      - name: Run test
        run: yarn test
      - name: Upload coverage
        uses: codecov/codecov-action@v3
